name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup env vars
        run: |
          echo "PYVER=2.7" >> $GITHUB_ENV

      - name: Install Pyenv
        run: |
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init -)"' >> ~/.bashrc

      - name: Install Python
        run: |
          TMPDIR=$(pwd)/tmp/ pyenv install -s ${PYVER}
          pyenv local ${PYVER}
          eval "$(pyenv init -)"

      - name: Test Install
        run:
          python -V
          which python
