name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup env vars
        run: |
          echo "PYVER=2.7" >> $GITHUB_ENV

      - name: Install Pyenv (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
          echo "$HOME/.pyenv/bin" >> $GITHUB_PATH
          echo "$HOME/.pyenv/shims" >> $GITHUB_PATH

      - name: Install Pyenv (Mac)
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install pyenv
          pyenv shims
          echo "$HOME/.pyenv/bin" >> $GITHUB_PATH
          echo "$HOME/.pyenv/shims" >> $GITHUB_PATH
        
      - name: Install Python
        run: |
          TMPDIR=$(pwd)/tmp/ pyenv install -s ${PYVER}
          pyenv local ${PYVER}

      - name: Test Install
        run: |
          python -V
          which python
