name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 2.7
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup env vars
        run: |
          echo "PYVER=2.7" >> $GITHUB_ENV

      - name: Install Pyenv
        run: |
          if which brew; then
            brew install pyenv
          else
            curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          fi
          
          echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
          echo "$HOME/.pyenv/bin" >> $GITHUB_PATH
          echo "$HOME/.pyenv/shims" >> $GITHUB_PATH
        
      - name: Install Python
        run: |
          TMPDIR=$(pwd)/tmp/ pyenv install -s ${PYVER}
          pyenv local ${PYVER}

      - name: Test Install
        run: |
          python -V
          which python
